-- MySQL Script generated by MySQL Workbench
-- Tue Mar 21 12:59:58 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stardunks` DEFAULT CHARACTER SET utf8 ;
USE `stardunks` ;

-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stardunks`.`products` ;

CREATE TABLE IF NOT EXISTS `stardunks`.`products` (
  `product_id` INT NOT NULL,
  `product_type_code` INT NULL,
  `supplier_id` INT NULL,
  `product_name` VARCHAR(255) NULL,
  `product_price` INT NULL,
  `other_product_details` VARCHAR(255) NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `products` (`product_id`, `product_type_code`, `supplier_id`, `product_name`, `product_price`, `other_product_details`) VALUES ('1', '1', '1', 'Sprinkled', '1.29', '1 pc.'), ('2', '1', '1', 'Chocolate', '1.49', '1 pc.');
INSERT INTO `products` (`product_id`, `product_type_code`, `supplier_id`, `product_name`, `product_price`, `other_product_details`) VALUES ('3', '1', '1', 'Maple', '1.49', '1 pc.'), ('4', '2', '2', 'Dunkaccino', '1,69', 'small');
INSERT INTO `products` (`product_id`, `product_type_code`, `supplier_id`, `product_name`, `product_price`, `other_product_details`) VALUES ('5', '3', '3', 'Steak Long Jim', '2,29', 'Steak wrap');
